version: '3.3'
services:
    app:
        build:
            context: .
            dockerfile: local.Dockerfile
        container_name: api-telered
        restart: always
        ports:
            - '3001:3001'
        environment:
            DB_HOSTNAME: db
            DB_NAME: dbapi
            DB_USER: user
            DB_PASSWORD: password
        external_links:
            - db:db
        depends_on:
            - db
