version: '3.3'
services:
    db:
        container_name: apimysql
        image: mysql:latest
        restart: always
        volumes:
            - ./db_data/db:/var/lib/mysql
            - ./db_scripts/scripts.sql:/docker-entrypoint-initdb.d/scripts.sql
        ports:
            - '3306:3306'
        expose:
            - '3306'
        hostname: dbapi
        environment:
            MYSQL_DATABASE: 'dbapi'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        links:
            - db
        ports:
            - 9191:80
        environment:
            MYSQL_USERNAME: user
            MYSQL_ROOT_PASSWORD: password
        depends_on:
            - db
